# Generated by Django 3.0.6 on 2020-05-16 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200516_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='brand_fk',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.BrandsModel'),
            preserve_default=False,
        ),
    ]
