# Generated by Django 3.0.6 on 2020-05-18 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_productmodel_brand_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='brand_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.BrandsModel', verbose_name='Brand'),
        ),
        migrations.CreateModel(
            name='SlidshowProductsModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('products', models.ManyToManyField(to='api.ProductModel', verbose_name='Products')),
            ],
            options={
                'verbose_name': 'Slideshow',
                'verbose_name_plural': 'Slideshow',
            },
        ),
    ]
