# Generated by Django 3.0.6 on 2020-05-18 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200518_0309'),
    ]

    operations = [
        migrations.AddField(
            model_name='slidshowproductsmodel',
            name='name',
            field=models.CharField(default='teste', max_length=200, verbose_name='Slideshow Name'),
            preserve_default=False,
        ),
    ]
